language: java

before_install: 
  - chmod +x gradlew

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b53783164e024ebb35d3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script: "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report -B"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: integration
      jdk: openjdk8
      script: "mvn integration-test -B"

#deploy:
#  provider: script
#  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
#  skip_cleanup: true
